#!/bin/sh

_root=~/.GermanBread/ani-cli-wrapper
script_dl="https://raw.githubusercontent.com/GermanBread/Bash-Scripts/master/ani-cli/ani-cli-wrapper"

uninstall() {
    rm -f ~/.local/bin/ani-cli ~/.cache/ani-hsts
    rm -rf ${_root}
    echo "Uninstalled sucessfully"
    exit 0
}

self_update() {
    curl -s ${script_dl} > /tmp/.ani-cli.update
    if ! cmp -s /tmp/.ani-cli.update ${_root}/exec; then
        mv /tmp/.ani-cli.update ${_root}/exec
        chmod +x ${_root}/exec
        exec $0 $*
    fi
}

update_git() {
    cd ${_root}/git
    git fetch               &>/dev/null
    git reset --hard master &>/dev/null
    git pull                &>/dev/null
}

patch_script() {
    sed -i "s,player_fn=\"mpv\",# See ${_root}/anirc,gm" ani-cli
}

restore_history() {
    [ -e ${_root}/ani-hsts ] && \
        cp ${_root}/ani-hsts ~/.cache/ani-hsts 2>/dev/null
}

get_options() {
    source ${_root}/anirc
    export player_fn
}

save_history() {
    cp ~/.cache/ani-hsts ${_root}/ani-hsts 2>/dev/null
}

[ "$1" == "--uninstall" ] && \
    uninstall

self_update $* # Pass script args to function
update_git
patch_script
get_options
restore_history
./ani-cli $*
save_history